// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// SystemServiceStateMetricConfig provides config for the system.service.state metric.
type SystemServiceStateMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SystemServiceStateMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for system_service metrics.
type MetricsConfig struct {
	SystemServiceState SystemServiceStateMetricConfig `mapstructure:"system.service.state"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		SystemServiceState: SystemServiceStateMetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for system_service metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}

// Deprecated: Use NewDefaultMetricsBuilderConfig.
func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return NewDefaultMetricsBuilderConfig()
}
