// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/system_service component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("system_service")
	ScopeName = "github.com/pierre-prevoteau/otel-receiver-service/servicereceiver"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
